const Group = require('../models/group');
const UserGroup = require('../models/userGroup');
const User = require('../models/user');

// Create a new group
exports.createGroup = async (req, res) => {
  try {
    const { name } = req.body;
    if (!name) {
      return res.status(400).json({ message: "Group name is required" });
    }

    // Create the group
    const newGroup = await Group.create({
      name: name,
      createdBy: req.user.id
    });

    // Automatically add the creator to the group as an Admin
    // Using the correct foreign key names generated by Sequelize
    await UserGroup.create({
      userId: req.user.id,
      groupId: newGroup.id,
      isAdmin: true
    });

    res.status(201).json({ message: "Group created successfully", group: newGroup });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to create group" });
  }
};

// Get all groups for the logged-in user
exports.getUserGroups = async (req, res) => {
  try {
    const userGroups = await UserGroup.findAll({
      where: { userId: req.user.id }
      // Removed the include statement temporarily to isolate the issue
    });

    // Format the response nicely. Since we removed include, we fetch groups manually
    const formattedGroups = await Promise.all(userGroups.map(async (ug) => {
      const group = await Group.findByPk(ug.groupId);
      return {
        id: group.id,
        name: group.name,
        isAdmin: ug.isAdmin
      };
    }));

    res.status(200).json({ groups: formattedGroups });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to fetch groups" });
  }
};

// Add a user to an existing group
exports.addUserToGroup = async (req, res) => {
  try {
    const { email, groupId } = req.body;

    // First check if the person making the request is an admin of this group
    const requesterUserGroup = await UserGroup.findOne({
      where: { userId: req.user.id, groupId: groupId }
    });

    if (!requesterUserGroup || !requesterUserGroup.isAdmin) {
      return res.status(403).json({ message: "Only admins can add members to this group" });
    }

    // Find the user they want to add
    const userToAdd = await User.findOne({ where: { email } });
    if (!userToAdd) {
      return res.status(404).json({ message: "User not found with this email" });
    }

    // Check if the user is already in the group
    const alreadyInGroup = await UserGroup.findOne({
      where: { userId: userToAdd.id, groupId: groupId }
    });

    if (alreadyInGroup) {
      return res.status(409).json({ message: "User is already in this group" });
    }

    // Add them to the group
    await UserGroup.create({
      userId: userToAdd.id,
      groupId: groupId,
      isAdmin: false // New members are not admins by default
    });

    res.status(200).json({ message: "User added to group successfully" });

  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to add user to group" });
  }
};
